function [temps, cons, Vmoteur, sortie] = conversion_fichier(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 30-Jan-2009 10:33:09

DELIMITER = '\t';
HEADERLINES = 24;

fid_in = fopen(fileToRead1,'r');
fid_out = fopen(strcat('mod_',fileToRead1),'w+');

while ~feof(fid_in)
   char = fread(fid_in, 1);
   if char == ','
      fwrite(fid_out, '.');
   else
      fwrite(fid_out, char);
   end
end

fclose(fid_in);
fclose(fid_out);

% Import the file
Data = importdata(strcat('mod_',fileToRead1), DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(Data);
for i = 1:length(vars)
    assignin('base', vars{i}, Data.(vars{i}));
end

data = Data.data;

%% Enlever le pré-déclenchement des données
temp=[];
for compteur = 1:length(data);
    if(data(compteur,2) ~= 0)
        temp = [temp ; data(compteur,:)];
    end
end
data = temp;
% Temps initial = 0 (plutôt que le temps du déclenchement);
data(:,1) = data(:,1) - data(1,1);

temps = data(:,1) / 1000;
cons = data(:,2);
Vmoteur = data(:,3);
sortie = data(:,4);